// apps/react-app/src/app/app.tsx
import { FC, useState } from 'react';
import styles from './app.module.scss';
import { Color, getColors } from './services/colors';
import { Country, getCountries } from './services/countries';


const App: FC = () => {
  const [textValue, setTextValue] = useState('textValue')
  const [passwordValue, setPasswordValue] = useState('')
  const [numberValue, setNumberValue] = useState(0)

  const [countries] = useState<Country[]>([{ code: '', name: '' }, ...getCountries()])

  const [colors] = useState<Color[]>([{ id: '', label: '' }, ...getColors()])

  const [selectedCountryCode, setSelectedCountryCode] = useState<Country['code'] | undefined>('')
  const [selectColorId, setSelectColorId] = useState<Color['id'] | undefined>('')


  return (
    <div className={styles.app}>
      <header>
        <h1>Welcome to Flowing Classroom!</h1>
      </header>
      <main>
        <div className="form-control">
          <label>Text</label>
          <input
            className='input_type1'
            type="text"
            placeholder="Text"
            value={textValue}
            onChange={(e) => setTextValue(e.target.value)}
          />
        </div>
        <div>
          <p>{textValue}</p>
        </div>

        <div className="form-control">
          <label>Text With Error</label>
          <input
            className='input_type1 input_type1--error'
            type="text"
            placeholder="Text With Error"
          />
        </div>

        <div className="form-control">
          <label>Text With Warning</label>
          <input
            className='input_type1 input_type1--warning'
            type="text"
            placeholder="Text With Warning"
          />
        </div>

        <div className="form-control">
          <label>Text With Success</label>
          <input
            className='input_type1 input_type1--success'
            type="text"
            placeholder="Text With Success"
          />
        </div>

        <div className="form-control">
          <label>Password</label>
          <input
            className='input_type1'
            type="password"
            placeholder="Password"
            value={passwordValue}
            onChange={(e) => setPasswordValue(e.target.value)}
          />
        </div>

        <div className="form-control">
          <label>Number</label>
          <input
            className='input_type1'
            type="number"
            placeholder="Number"
            value={numberValue}
            min={0}
            max={100}
            step={1}
            onChange={(e) => setNumberValue(e.target.valueAsNumber)}
          />
        </div>

        <div className="form-control">
          <label>Country</label>
          <select
            className='select_style1'
            value={selectedCountryCode}
            onChange={e => {
              setSelectedCountryCode(e.target.value)
            }}>
            {countries.map(({ code, name }) => (
              <option
                key={code}
                value={code}
              >{name}</option>
            ))}
          </select>
        </div>

        <pre>{JSON.stringify(countries.find(c => c.code === selectedCountryCode) || {})}</pre>

        <div className="form-control">
          <label>Color</label>
          <select
            className='select_style1'
            value={selectColorId}
            onChange={e => {
              setSelectColorId(e.target.value)
            }}>
            {colors.map(({ id, label }) => (
              <option
                key={id}
                value={id}
              >{label}</option>
            ))}
          </select>
        </div>

        <pre>{JSON.stringify(colors.find(c => c.id === selectColorId) || {})}</pre>
      </main>
    </div>
  );
}

export default App;

// apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { Color, ColorsService } from './services/colors.service';
import { CountriesService, Country } from './services/countries.services';

@Component({
  selector: 'flowing-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  textValue?: string = 'textValue';
  passwordValue?: string = '';
  numberValue?: number = 0;

  countries: Country[];
  colors: Color[];

  selectedCountyCode: Country['code'] | undefined;
  selectedCounty: Country | undefined;

  selectColorId: Color['id'] | undefined;
  selectColor: Color | undefined;

  constructor(
    colorsService: ColorsService,
    countriesService: CountriesService
  ) {
    this.countries = [
      { code: '', name: '' },
      ...countriesService.getCountries(),
    ];
    this.colors = [{ id: '', label: '' }, ...colorsService.getColors()];
  }

  onInputTextChange(event: Event): void {
    const newValue = (event.target as HTMLInputElement | null)?.value;
    this.textValue = newValue;
  }

  onInputNumberChange(event: Event): void {
    const newValue = (event.target as HTMLInputElement | null)?.valueAsNumber;
    this.numberValue = newValue;
  }

  onCountryChange(newValue: Country['code']): void {
    this.selectedCountyCode = newValue;
    this.selectedCounty = this.countries.find((c) => c.code === newValue);
  }

  onColorChange(newValue: Color['id']): void {
    this.selectColorId = newValue;
    this.selectColor = this.colors.find((c) => c.id === newValue);
  }
}

<header>
  <h1>Welcome to Flowing Classroom!</h1>
</header>
<main>
  <div class="form-control">
    <label>Text</label>
    <input
      class="input_type1"
      type="text"
      placeholder="Text"
      [value]="textValue"
      (input)="onInputTextChange($event)"
    />
  </div>
  <div>
    <p>{{ textValue }}</p>
  </div>

  <div class="form-control">
    <label>Text With Error</label>
    <input
      class="input_type1 input_type1--error"
      type="text"
      placeholder="Text With Error"
    />
  </div>

  <div class="form-control">
    <label>Text With Warning</label>
    <input
      class="input_type1 input_type1--warning"
      type="text"
      placeholder="Text With Warning"
    />
  </div>

  <div class="form-control">
    <label>Text With Success</label>
    <input
      class="input_type1 input_type1--success"
      type="text"
      placeholder="Text With Success"
    />
  </div>

  <div class="form-control">
    <label>Password</label>
    <input
      class="input_type1"
      type="password"
      placeholder="Password"
      [value]="passwordValue"
    />
  </div>

  <div class="form-control">
    <label>Number</label>
    <input
      class="input_type1"
      type="number"
      placeholder="Number"
      [value]="numberValue"
      min="0"
      max="100"
      step="1"
    />
  </div>

  <div class="form-control">
    <label>Country</label>
    <select
      class="select_style1"
      [ngModel]="selectedCountyCode"
      (ngModelChange)="onCountryChange($event)"
    >
      <option *ngFor="let country of countries" [value]="country.code">
        {{ country.name }}
      </option>
    </select>
  </div>

  <pre>{{ selectedCounty | json }}</pre>

  <div class="form-control">
    <label>Color</label>
    <select
      class="select_style1"
      [ngModel]="selectColorId"
      (ngModelChange)="onColorChange($event)"
    >
      <option *ngFor="let color of colors" [value]="color.id">
        {{ color.label }}
      </option>
    </select>
  </div>

  <pre>{{ selectColor | json }}</pre>
</main>
